# Generated by Django 4.0.5 on 2022-10-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='hora',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='materia',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
