# Generated by Django 4.0.5 on 2022-10-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_materia_hora_materia_name_materia_profesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
