# Generated by Django 4.0.5 on 2022-10-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_seccion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='hora',
            field=models.TimeField(blank=True),
        ),
    ]
