# Generated by Django 4.0.5 on 2022-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_alter_materia_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
