# Generated by Django 4.0.5 on 2022-10-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_alter_materia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='materia',
            name='profesor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='materia',
            name='profesor_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
