# Generated by Django 4.0.5 on 2022-10-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0005_pomodoro_pregunta_seccion_alter_pregunta_apropiacion_and_more'),
        ('MAIN', '0006_alter_materia_hora_alter_materia_profesor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='')),
                ('Materia', models.ManyToManyField(to='MAIN.materia')),
                ('Seccion', models.ManyToManyField(to='MAIN.seccion')),
                ('docPregunta', models.ManyToManyField(to='ESTUDIO.pregunta')),
            ],
        ),
    ]
