# Generated by Django 4.0.5 on 2022-10-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0011_alter_pregunta_apropiacion'),
        ('MAIN', '0007_register_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Seccion',
            field=models.ManyToManyField(blank=True, to='MAIN.seccion'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='docPregunta',
            field=models.ManyToManyField(blank=True, to='ESTUDIO.pregunta'),
        ),
    ]
