# Generated by Django 4.0.5 on 2022-10-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0008_alter_documento_seccion_alter_documento_docpregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Materia',
            field=models.ManyToManyField(blank=True, to='MAIN.materia'),
        ),
    ]
