# Generated by Django 4.1.2 on 2022-10-12 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0011_alter_pregunta_apropiacion'),
        ('MAIN', '0009_alter_documento_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='Materia',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Seccion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='docPregunta',
        ),
        migrations.AddField(
            model_name='documento',
            name='Materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MAIN.materia'),
        ),
        migrations.AddField(
            model_name='documento',
            name='Seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MAIN.seccion'),
        ),
        migrations.AddField(
            model_name='documento',
            name='docPregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ESTUDIO.pregunta'),
        ),
    ]
