# Generated by Django 4.0.5 on 2022-10-16 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0010_remove_documento_materia_remove_documento_seccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MAIN.register'),
        ),
    ]
