# Generated by Django 4.0.5 on 2022-10-29 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MAIN', '0013_seccion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prioridad', models.CharField(choices=[('Bajo', 'Bajo'), ('Media', 'Medio'), ('Alto', 'Alto')], default='Bajo', max_length=20)),
                ('fecha', models.DateField(null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MAIN.materia')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
