# Generated by Django 4.1.2 on 2022-10-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0014_tarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
