# Generated by Django 4.1.2 on 2022-10-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0015_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='realizado',
        ),
    ]
