# Generated by Django 4.1.2 on 2022-10-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0017_alter_tarea_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('Bajo', 'Bajo'), ('Media', 'Medio'), ('Alto', 'Alto')], default='Bajo', max_length=20),
        ),
    ]
