# Generated by Django 4.1.2 on 2022-11-02 16:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0019_remove_tarea_realizado_alter_tarea_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='horario',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=9, null=True),
        ),
    ]
