# Generated by Django 4.1.2 on 2022-11-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0020_materia_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='materia',
            name='otros_archivos',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
