# Generated by Django 4.1.2 on 2022-11-02 20:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0022_rename_otros_archivos_materia_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='horario',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=100, null=True),
        ),
    ]
