# Generated by Django 4.0.5 on 2022-11-02 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MAIN', '0023_alter_materia_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='Seccion',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='archivos',
        ),
        migrations.AddField(
            model_name='documento',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
