# Generated by Django 4.0.5 on 2022-11-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0024_remove_documento_seccion_remove_materia_archivos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Materia',
            new_name='materia',
        ),
    ]
