# Generated by Django 4.1.2 on 2022-11-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0025_rename_materia_documento_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='aula',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
