# Generated by Django 4.0.5 on 2022-11-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0027_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='key',
            field=models.FileField(blank=True, null=True, upload_to='token files/'),
        ),
    ]
