# Generated by Django 4.0.5 on 2022-11-18 15:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0028_alter_calendar_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='horario',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=100, null=True),
        ),
    ]
