# Generated by Django 4.0.5 on 2022-11-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0028_alter_calendar_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
