# Generated by Django 4.0.5 on 2022-11-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0029_alter_materia_horario'),
        ('MAIN', '0029_delete_calendar'),
    ]

    operations = [
    ]
