# Generated by Django 4.0.5 on 2022-11-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0030_merge_0029_alter_materia_horario_0029_delete_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='profesor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
