# Generated by Django 4.0.5 on 2022-10-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='ultima_vez',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tarea',
            name='realizado',
            field=models.BooleanField(null=True),
        ),
    ]
