# Generated by Django 4.0.5 on 2022-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0002_pregunta_name_pregunta_respuesta_pregunta_ultima_vez_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
