# Generated by Django 4.0.5 on 2022-10-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0003_alter_tarea_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
