# Generated by Django 4.0.5 on 2022-10-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_alter_materia_hora_alter_materia_profesor_and_more'),
        ('ESTUDIO', '0004_alter_pregunta_name_alter_pregunta_respuesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MAIN.seccion'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='apropiacion',
            field=models.IntegerField(choices=[(1, 'Otra Vez'), (2, 'Dificil'), (3, 'Bien'), (4, 'Facil')]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.TextField(max_length=200),
        ),
    ]
