# Generated by Django 4.0.5 on 2022-10-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0005_pomodoro_pregunta_seccion_alter_pregunta_apropiacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='apropiacion',
            field=models.IntegerField(choices=[(1, 'Otra Vez'), (2, 'Dificil'), (3, 'Bien'), (4, 'Facil')], null=True),
        ),
    ]
