# Generated by Django 4.0.5 on 2022-10-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0008_alter_pregunta_apropiacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='apropiacion',
            field=models.IntegerField(choices=[(1, 'Otra Vez'), (2, 'Dificil'), (3, 'Bien'), (4, 'Facil')], default='Default'),
        ),
    ]
