# Generated by Django 4.1.2 on 2022-10-22 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0012_pregunta_user_alter_pregunta_ultima_vez'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestasCerradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuestas_cerradas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESTUDIO.respuestascerradas'),
        ),
    ]
