# Generated by Django 4.1.2 on 2022-10-22 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ESTUDIO', '0013_respuestascerradas_pregunta_respuestas_cerradas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='respuestas_cerradas',
        ),
        migrations.AddField(
            model_name='respuestascerradas',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESTUDIO.pregunta'),
        ),
        migrations.AddField(
            model_name='respuestascerradas',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
