# Generated by Django 4.1.2 on 2022-10-22 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0014_remove_pregunta_respuestas_cerradas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestascerradas',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta_cerrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESTUDIO.respuestascerradas'),
        ),
    ]
