# Generated by Django 4.1.2 on 2022-10-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0017_remove_pregunta_respuesta_cerrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestascerradas',
            old_name='respuesta',
            new_name='respuesta_cerrada',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
