# Generated by Django 4.1.2 on 2022-10-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0013_seccion_user'),
        ('ESTUDIO', '0018_rename_respuesta_respuestascerradas_respuesta_cerrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestascerradas',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='respuestascerradas',
            name='apropiacion',
            field=models.IntegerField(choices=[(1, 'Otra Vez'), (2, 'Dificil'), (3, 'Bien'), (4, 'Facil')], default=1),
        ),
        migrations.AddField(
            model_name='respuestascerradas',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='respuestascerradas',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MAIN.seccion'),
        ),
        migrations.AddField(
            model_name='respuestascerradas',
            name='ultima_vez',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuestascerradas',
            name='respuesta_cerrada',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
