# Generated by Django 4.1.2 on 2022-10-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0021_remove_respuestascerradas_apropiacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestascerradas',
            name='verdadera',
            field=models.BooleanField(default=False),
        ),
    ]
