# Generated by Django 4.1.2 on 2022-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0022_respuestascerradas_verdadera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestascerradas',
            name='verdadera',
        ),
        migrations.AddField(
            model_name='respuestascerradas',
            name='respuesta_verdadera',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
