# Generated by Django 4.1.2 on 2022-10-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0023_remove_respuestascerradas_verdadera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestascerradas',
            name='respuesta_cerrada',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
