# Generated by Django 4.1.2 on 2022-10-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0024_alter_respuestascerradas_respuesta_cerrada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
