# Generated by Django 4.0.5 on 2022-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0025_delete_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='num_repaso',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
