# Generated by Django 4.0.5 on 2022-11-16 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0026_pregunta_num_repaso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='ultima_vez',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 16, 13, 35, 10, 940734), null=True),
        ),
    ]
