# Generated by Django 4.0.5 on 2022-11-16 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0027_alter_pregunta_ultima_vez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='ultima_vez',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
