# Generated by Django 4.0.5 on 2022-11-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0028_alter_pregunta_ultima_vez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestascerradas',
            name='respuesta_cerrada',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='respuestascerradas',
            name='respuesta_verdadera',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
