# Generated by Django 4.0.5 on 2022-11-23 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIO', '0029_alter_respuestascerradas_respuesta_cerrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='ultima_vez',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
